name: Deploy MERN (Self-Hosted Runner)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Fix workspace permissions
        run: sudo chown -R $USER:$USER $GITHUB_WORKSPACE || true

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' 

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          clean: false

      - name: Install & Build Frontend
        working-directory: ./frontend
        run: |
          npm ci --prefer-offline --no-audit --no-fund --progress=false
          npm run build

      - name: Install Backend dependencies
        working-directory: ./backend
        run: npm ci --omit=dev

      - name: Restart Backend
        working-directory: ./backend
        run: |
          pm2 restart backend || pm2 start index.js --name backend
          pm2 save

      - name: Reload Nginx
        run: sudo systemctl reload nginx
